from app.db.models.user import User
type nul > app\__init__.py
type nul > app\core\__init__.py
type nul > app\db\__init__.py
type nul > app\db\models\__init__.py
type nul > app\db\repositories\__init__.py
type nul > app\api\__init__.py
type nul > app\api\v1\__init__.py
type nul > app\api\v1\routes\__init__.py
type nul > app\api\v1\dependencies\__init__.py
type nul > app\services\__init__.py
type nul > app\services\ai\__init__.py
type nul > app\services\auth\__init__.py
type nul > app\services\interview\__init__.py
type nul > app\schemas\__init__.py
type nul > app\utils\__init__.py